### ISSUE TITLE
Changing timezone unconditionally

### ISSUE THREAD

**Issue by mrbig** [viesapi/viesapi-php-client#1]
The client changes the system timezone to Etc/UTC in the VIESAPIClient::__construct method unconditionally. This can lead to sideffects in applications where other timezone is in use.

I recommend using `gmdate()` instead of `date()` so that no timezone change is necessary.
If this is not enough the timezone could be changed temporarily in the methods where it is necessary then changed back to the original.

**Comment by viesapi** [comment]
Function date_default_timezone_set() was removed from constructor. From now on, dates returned will have the default time zone of the PHP server.
